import = ["/home/alex/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 18.0

[font.bold]
family = "ComicCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ComicCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ComicCode Nerd Font"
style = "Italic"

[font.normal]
family = "ComicCode Nerd Font"
style = "Regular"

[window.padding]
x = 6
y = 6
