["MPK mini"]
enabled = true
midi-input = "MPK mini"
global-macros = "mpk-mini/global.mm"
virtual-sustain-callback = "read state; echo $state sustain | speak-it"
enable-callback = "read state; echo $state MPK | speak-it"
subprofile-callback = "read subprofile; echo subprofile $subprofile | speak-it"
enable-trigger = "[E4|F4|G4|A4]"
cycle-subprofiles-trigger = "[D4|E4|F4|G4]"
debounce-callbacks = true
["MPK mini".default]
macros = "mpk-mini/default.mm"
["MPK mini".mc]
macros = "mpk-mini/mc.mm"
["MPK mini".ll]
macros = "mpk-mini/ll.mm"
