["MPK mini"]
enabled = true
midi-input = "MPK mini"
global-macros = "mpk-mini/global.mm"
virtual-sustain-callback = "read state; echo $state sustain | piper --model ~/voices/en_US-hfc_male-medium.onnx --output_raw | pw-play --format s16 --rate 22050 --channels 1 -"
enable-callback = "read state; echo $state MPK | piper --model ~/voices/en_US-hfc_male-medium.onnx --output_raw | pw-play --format s16 --rate 22050 --channels 1 -"
subprofile-callback = "read subprofile; echo subprofile $subprofile | piper --model ~/voices/en_US-hfc_male-medium.onnx --output_raw | pw-play --format s16 --rate 22050 --channels 1 -"
enable-trigger = "[E4|F4|G4|A4]"
cycle-subprofiles-trigger = "[D4|E4|F4|G4]"
debounce-callbacks = true
["MPK mini".default]
macros = "mpk-mini/default.mm"
["MPK mini".mc]
macros = "mpk-mini/mc.mm"
["MPK mini".ll]
macros = "mpk-mini/ll.mm"
